# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ab9797c8ce33a8b51b30861dee88dd1faaa620bbab22bd6993574d134bffbe21a1bd277add4c2c07aa3a6705cbda4bebd641158af7caed58a1bd5a91cc5478c

test:
  secret_key_base: 359c2956d1caf4d20ace6b67e1a839fc83228a80b1da49faffd24f6a1197a98af86d15192a5b9c2c566c1d231d0913b85c8866a1b49e043b2dc2af903ff7801e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
